name: Java Documentation with Maven

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Build PDF with Maven
        working-directory: ./demo
        run: mvn pdf:pdf --file pom.xml
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Documentation
          path: demo/target/pdf/demo.pdf
